package net.kkung.libsass;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
/**
 * JNA Wrapper for library <b>libsass</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface LibsassLibrary extends Library {
	public static final String JNA_LIBRARY_NAME = "sass";
	public static final NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(LibsassLibrary.JNA_LIBRARY_NAME);
	public static final LibsassLibrary INSTANCE = (LibsassLibrary)Native.loadLibrary(LibsassLibrary.JNA_LIBRARY_NAME, LibsassLibrary.class);
	public static final int SASS_STYLE_EXPANDED = (int)1;
	public static final int SASS_STYLE_NESTED = (int)0;
	public static final int SASS_STYLE_COMPACT = (int)2;
	public static final int SASS_STYLE_COMPRESSED = (int)3;
	/**
	 * Original signature : <code>sass_context* sass_new_context()</code><br>
	 * <i>native declaration : line 40</i>
	 */
	sass_context sass_new_context();
	/**
	 * Original signature : <code>sass_file_context* sass_new_file_context()</code><br>
	 * <i>native declaration : line 41</i>
	 */
	sass_file_context sass_new_file_context();
	/**
	 * Original signature : <code>sass_folder_context* sass_new_folder_context()</code><br>
	 * <i>native declaration : line 42</i>
	 */
	sass_folder_context sass_new_folder_context();
	/**
	 * Original signature : <code>void sass_free_context(sass_context*)</code><br>
	 * <i>native declaration : line 44</i>
	 */
	void sass_free_context(sass_context ctx);
	/**
	 * Original signature : <code>void sass_free_file_context(sass_file_context*)</code><br>
	 * <i>native declaration : line 45</i>
	 */
	void sass_free_file_context(sass_file_context ctx);
	/**
	 * Original signature : <code>void sass_free_folder_context(sass_folder_context*)</code><br>
	 * <i>native declaration : line 46</i>
	 */
	void sass_free_folder_context(sass_folder_context ctx);
	/**
	 * Original signature : <code>int sass_compile(sass_context*)</code><br>
	 * <i>native declaration : line 48</i>
	 */
	int sass_compile(sass_context ctx);
	/**
	 * Original signature : <code>int sass_compile_file(sass_file_context*)</code><br>
	 * <i>native declaration : line 49</i>
	 */
	int sass_compile_file(sass_file_context ctx);
	/**
	 * Original signature : <code>int sass_compile_folder(sass_folder_context*)</code><br>
	 * <i>native declaration : line 50</i>
	 */
	int sass_compile_folder(sass_folder_context ctx);
}
