package net.kkung.libsass;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
/**
 * <i>native declaration : line 11</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class sass_options extends Structure {
	public int output_style;
	/// C type : char*
	public Pointer include_paths;
	public sass_options() {
		super();
		initFieldOrder();
	}
	protected void initFieldOrder() {
		setFieldOrder(new String[]{"output_style", "include_paths"});
	}
	/// @param include_paths C type : char*
	public sass_options(int output_style, Pointer include_paths) {
		super();
		this.output_style = output_style;
		this.include_paths = include_paths;
		initFieldOrder();
	}
	public static class ByReference extends sass_options implements Structure.ByReference {
		
	};
	public static class ByValue extends sass_options implements Structure.ByValue {
		
	};
}
